-- Blog with Supabase Comments — Database Setup
-- Run this in Supabase SQL Editor after creating your project

-- 1. Posts table (admin writes via dashboard)
create table posts (
  id bigint generated by default as identity,
  title text not null,
  content text not null,
  slug text unique not null,
  published boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (id)
);

alter table posts enable row level security;

create policy "Posts public read"
  on posts for select
  using (published = true);

-- 2. Comments table (authenticated users)
create table comments (
  id bigint generated by default as identity,
  post_id bigint references posts(id) on delete cascade,
  user_id uuid references auth.users(id),
  user_name text not null,
  content text not null,
  created_at timestamptz default now(),
  primary key (id)
);

alter table comments enable row level security;

create policy "Comments public read"
  on comments for select
  using (true);

create policy "Comments auth insert"
  on comments for insert
  with check (
    auth.role() = 'authenticated'
    and user_id = auth.uid()
  );

create policy "Comments auth update own"
  on comments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- 3. Index for comment lookups
create index idx_comments_post_id on comments(post_id);
